#!/bin/sh


CAFFE_ROOT="/work/01932/dineshj/CS381V/caffe_install_scripts/caffe"
CAFFE_TOOL="${CAFFE_ROOT}/build/tools"
CAFFE_DATA="${CAFFE_ROOT}/data/flickr_style"
CAFFE_MODEL="${CAFFE_ROOT}/models/bvlc_reference_caffenet/bvlc_reference_caffenet.caffemodel"

DATA_DIR="/work/04018/wxie/maverick/visual_recognition/data"

    # convert image to lmdb
    train_db='train-lmdb'
    if [ ! -d "$train_db" ]; then
        ${CAFFE_TOOL}/convert_imageset -resize_height 256 -resize_width 256 -shuffle / ${DATA_DIR}/train.txt ${DATA_DIR}/${train_db}
        read -p $'Construct train-lmdb.\nPress [Enter] key to continue.'
    fi
    test_db='test-lmdb'
    if [ ! -d "$test_db" ]; then
        ${CAFFE_TOOL}/convert_imageset -resize_height 256 -resize_width 256 -shuffle / ${DATA_DIR}/test.txt ${DATA_DIR}/${test_db}
        read -p $'Construct test-lmdb.\nPress [Enter] key to continue.'
    fi

