#!/bin/bash
#-----------------------------------------------------------------
# Example SLURM job script to run serial applications on TACC's
# Stampede system.
#
# This script requests one core (out of 16) on one node. The job
# will have access to all the memory in the node.  Note that this
# job will be charged as if all 16 cores were requested.
#-----------------------------------------------------------------

#SBATCH -n 1  
#SBATCH -A CS381V-Visual-Recogn
#SBATCH -p gpu
#SBATCH -t 01:30:00        # run time (hh:mm:ss) - 
#SBATCH -o finetune_subset_%j.out
#SBATCH --mail-user=wxie@utexas.edu
#SBATCH --mail-type=all    # email me when the job finishes


# Load any necessary modules (these are examples)
# Loading modules in the script ensures a consistent environment.
#module load fftw3
#module load hdf5

# Launch the executable named
./finetune_subset.sh

